archives:
  - files:
      # Only include built binary in archive
      - 'none*'
    formats: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

builds:
  - # Special binary naming is only necessary for Terraform CLI 0.12
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
      - goarch: arm64
        goos: freebsd
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{.Version}}

checksum:
  #extra_files:
  #  - glob: 'terraform-registry-manifest.json'
  #    name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - cmd: gpg2
    artifacts: checksum
    args: [
      "--batch",
      "--local-user",
      "{{ .Env.GPG_FINGERPRINT }}",
      "--output",
      "${signature}",
      "--detach-sign",
      "${artifact}",
    ]
    output: true
