// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"

	graphql "github.com/hasura/go-graphql-client"
	mock "github.com/stretchr/testify/mock"
)

// MonteCarloClient is an autogenerated mock type for the MonteCarloClient type
type MonteCarloClient struct {
	mock.Mock
}

// ExecRaw provides a mock function with given fields: ctx, query, variables, options
func (_m *MonteCarloClient) ExecRaw(ctx context.Context, query string, variables map[string]interface{}, options ...graphql.Option) ([]byte, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query, variables)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, ...graphql.Option) ([]byte, error)); ok {
		return rf(ctx, query, variables, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, ...graphql.Option) []byte); ok {
		r0 = rf(ctx, query, variables, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}, ...graphql.Option) error); ok {
		r1 = rf(ctx, query, variables, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mutate provides a mock function with given fields: ctx, m, variables, options
func (_m *MonteCarloClient) Mutate(ctx context.Context, m interface{}, variables map[string]interface{}, options ...graphql.Option) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, m, variables)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, map[string]interface{}, ...graphql.Option) error); ok {
		r0 = rf(ctx, m, variables, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Query provides a mock function with given fields: ctx, q, variables, options
func (_m *MonteCarloClient) Query(ctx context.Context, q interface{}, variables map[string]interface{}, options ...graphql.Option) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, q, variables)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, map[string]interface{}, ...graphql.Option) error); ok {
		r0 = rf(ctx, q, variables, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMonteCarloClient creates a new instance of MonteCarloClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonteCarloClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonteCarloClient {
	mock := &MonteCarloClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
