name: Terraform Provider Tests

on:
  pull_request:
      branches:
        - master
  workflow_call:
    secrets:
      ACC_TEST_MC_API_KEY_ID:
        description: 'Monte Carlo API Key ID'
        required: true
      ACC_TEST_MC_API_KEY_TOKEN:
        description: 'Monte Carlo API Key Token'
        required: true
      ACC_TEST_BQ_SERVICE_ACCOUNT:
        description: 'BigQuery Service Account'
        required: true
      ACC_TEST_PG_HOST:
        description: 'Postgres Host'
        required: true
      ACC_TEST_PG_PORT:
        description: 'Postgres Port'
        required: true
      ACC_TEST_PG_DATABASE:
        description: 'Postgres Database'
        required: true
      ACC_TEST_PG_USER:
        description: 'Postgres User'
        required: true
      ACC_TEST_PG_PASSWORD:
        description: 'Postgres Password'
        required: true

permissions:
  # Permission for checking out code
  contents: read

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: 'go.mod'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.*'
          terraform_wrapper: false
      - run:
          go test -v ./... -coverprofile=coverage.out
        env:
          TF_ACC: '1'
          MC_API_KEY_ID: ${{ secrets.ACC_TEST_MC_API_KEY_ID }}
          MC_API_KEY_TOKEN: ${{ secrets.ACC_TEST_MC_API_KEY_TOKEN }}
          BQ_SERVICE_ACCOUNT: ${{ secrets.ACC_TEST_BQ_SERVICE_ACCOUNT }}
          PG_HOST: ${{ secrets.ACC_TEST_PG_HOST }}
          PG_PORT: ${{ secrets.ACC_TEST_PG_PORT }}
          PG_DATABASE: ${{ secrets.ACC_TEST_PG_DATABASE }}
          PG_USER: ${{ secrets.ACC_TEST_PG_USER }}
          PG_PASSWORD: ${{ secrets.ACC_TEST_PG_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage.out
